### ISSUE TITLE
Restrict nesting

### ISSUE THREAD

**Issue by mmende** [lytc/react-sortly#10]
I am trying to restrict the nesting so that items at the top level and one level below can only be sorted. Furthermore for deeper nested items (path.length > 1) it should not be possible to drop them as first or second level item. To accomplish that I use the onMove handler to check the dragged items path against it's original items path. The handler looks something like this:

```js
const onMove = (newItems, dragIndex, newIndex) => {
  const draggedItem = newItems[newIndex];
  const originalItem = items.find(({ id }) => id === draggedItem.id);
  if (!originalItem) {
    return false; // Just to assure originalItem was found...
  }
  const originalNestingLevel = originalItem.path.length;
  const newNestingLevel = draggedItem.path.length;
  
  // Prevent changing the nesting for items with path.length <= 1
  if (originalNestingLevel <= 1 && originalNestingLevel !== newNestingLevel) {
    return false;
  }

  // Prevent changing the nesting for items with path.length > 1
  // to path.length <= 1
  if (originalNestingLevel > 1 && newNestingLevel <= 1) {
    return false;
  }
  return true;
};
```

The sort only part works perfectly fine.
The nesting part also works fine when items at the second level (path.length = 1) have children. However if they don't have any children it is not possible to drag a deeper nested item from another second level item below this childless item for some reason.

Do you have any ideas how to solve this problem?
Thanks in advance and thanks for this awesome component.
I was looking ages for nested dnd.

**Comment by vikramkakkar06** [comment]
@mmede is your issue soved can you help me how you fixed this in one level nesting

**Comment by mmende** [comment]
Unfortunately not really. However I managed to get it to work as expected in a pretty hacky way by adding hidden placeholders on the path.length <= 1 items. These placeholders come with some disadvantages like smaller mouse interaction area on the parent item and pre- / postprocessing of the items for every rerender of the list. If you however think this solution would still fit your requirements let me know and I can explain it in more detail.
