### ISSUE TITLE
is react-dnd-html5-backend still required?

### ISSUE THREAD

**Issue by RSSfeed** [lytc/react-sortly#11]
As of Feb 7, this repository has been marked read-only since it got merged into react-dnd (see
https://github.com/react-dnd/react-dnd-html5-backend/commit/1d7573c1eb85d040fd1029715e7dbb0e5121e9b3)

**Comment by lytc** [comment]
@RSSfeed We don't require any particular backend, you can you any backend that supported by DnD. Sorry for late reply!
