### ISSUE TITLE
Collapse tree node

### ISSUE THREAD

**Issue by jowusu837** [lytc/react-sortly#13]
I think it will be a great feature if a tree node with children can be collapsed the same way it can be expanded.

**Comment by LyTranCong** [comment]
@jowusu837 Could you describe more?
Is `collapsed` prop in `itemRenderer` doesn't work for you?

**Comment by jowusu837** [comment]
@LyTranCong I don't think that prop is there?

**Comment by LyTranCong** [comment]
@jowusu837 I'm not really understand what you need. Could you post example code and describe what you need here?
