### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by fourpixels** [lytc/react-sortly#15]
As DND package is updated (and since this one imports `*` dnd version), the sample usage is no longer working. DND package does *not* export `DragDropContext`.

@lytc is this package still supported?

**Comment by lytc** [comment]
@fourpixels I'm working on the upgrade to support for the latest DnD and also React but don't have time to finish that yet. Could you try with DnD version 8?

**Comment by MartinN3** [comment]
Use libraries versioned in package.json - Examples section.

**Comment by lytc** [comment]
@fourpixels New major version has been released. Let me know if it's working for you!
Noticed that the new 2.x version is not compatible with 1.x!
