### ISSUE TITLE
Dragging Ghost

### ISSUE THREAD

**Issue by andrew-rubiano-projectstudio** [lytc/react-sortly#4]
![demo](https://user-images.githubusercontent.com/41843671/47609368-a05c6680-da02-11e8-8d11-c79f2a020948.gif)

I am using your library nested inside of react-dnd-HOC and it works great! The only issue I've noticed is that the ghosting is picking up the whole parent container instead of just itself and its descendants. Any thoughts on how to remove/correct the ghosting?

**Comment by lytc** [comment]
@andrew-rubiano-projectstudio I'm guessing that something wrong with `connectDragPreview`. Could you post your code here?

**Comment by lytc** [comment]
Is it happens for you on example page as well? https://lytc.github.io/react-sortly
If not then something wrong with your code!

**Comment by ptmaroct** [comment]
I am facing the same issue when the draggable item is a collapsible. The preview is wrong and has multiple items in it when just a single item is being dragged. Any update on this?
