### ISSUE TITLE
Did anyone tried to unit test it using jest + enzyme?

### ISSUE THREAD

**Issue by elbrus** [lytc/react-sortly#5]
As you figured I run unit tests using jest and enzyme.
Problem is that item renderer isn't triggered even, when component is mounted. So I can't make tests against rendered item.

FYI, I'm not writing tests for this lib. I'm writing tests in my own project, where react-sortly is used inside some components.

**Comment by lytc** [comment]
@elbrus What's your test code look like?

**Comment by elbrus** [comment]
I don't have anything special in my test case.
There is a component AA, which besides some other stuff renders `Sortly` as well.
I use Enzyme to mount AA, everything works as expected except Sortly prop `itemRenderer`, it's not being called.
I debugged it, passed data is correct and not empty, but my breakpoint inside function (which is passed to itemRenderer) isn't triggered.

**Comment by lytc** [comment]
Probably you're forgot to wrap the component you want to test with react-dnd context.
For example:
```
const MyTree = () => <Sortly items={items} />
const MyApp = () => (
  <div>
    ....
    <MyTree />
  </div>
);
export default DragDropContext(HTML5Backend)(MyApp);
```
Then when testing the `MyTree` component we would need to wrap it with dnd-context because in the app source we just wrapped it in the `MyApp` component.
```
import TestBackend from 'react-dnd-test-backend';
import { DragDropContext } from 'react-dnd';
import { mount } from 'enzyme';

function wrapWithDndTestContext(DecoratedComponent) {
  return DragDropContext(TestBackend)(
    () => <DecoratedComponent />
  );
}

it('should work', () => {
  const MyTreeWithDndContext = wrapWithDndTestContext(MyTree);
  const wrapper = mount(<MyTreeWithDndContext />);
})
```
http://react-dnd.github.io/react-dnd/docs/testing

**Comment by elbrus** [comment]
aaah, dumb me :))
closing it
thanks!!
