### ISSUE TITLE
maxDepth Example

### ISSUE THREAD

**Issue by EricFries** [lytc/react-sortly#7]
Great library!  

I'm trying to create a list that only allows one level of nesting. I've tried setting `maxDepth` to 0, 1 and 2 each each value seems to allow for an infinite level of nesting.  Is there a working example using `maxDepth`?

**Comment by lytc** [comment]
This is a bug since recently changes @EricFries. Fixed in 1.5.4!

**Comment by EricFries** [comment]
Great, thank you!

**Comment by alexandregiordanelli** [comment]
I have the same issue with this version 3.0.0-alpha.5.

**Comment by ly-tc** [comment]
@alexandregiordanelli 
I fixed this in 3.0.4
Code sandbox demo https://codesandbox.io/s/sparkling-leftpad-j383v?fontsize=14&hidenavigation=1&theme=dark

**Comment by alexandregiordanelli** [comment]
There is still a bug when I set up maxDepth to one.
![maxdepth1](https://user-images.githubusercontent.com/1518223/71513098-c7692f00-2877-11ea-9824-44d07a95a43b.gif)
