### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by timsu** [lytc/react-sortly#8]
Hi there!

We're interested in using react-sortly for a project, it looks like a nice wrapper around react-dnd. However, I'm worried there's no LICENSE on the project (other than in package.json). Can you clarify what the license is for this code? Thanks!

**Comment by lytc** [comment]
Added license file @timsu !

**Comment by timsu** [comment]
Awesome thanks.

BTW, noticed a typo here:
https://github.com/lytc/react-sortly/blob/master/src/Sortly.js#L26

You have the prop named "ondDragEnd" which has an extra d :)
